[package]
name = "ocnus"
version = "0.0.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ocnus"
crate-type = ["lib"]

[dependencies]
approx.workspace = true
chrono.workspace = true
derive_builder.workspace = true
derive_more.workspace = true
dtw.workspace = true
itertools.workspace = true
log.workspace = true
nalgebra.workspace = true
num-traits.workspace = true
paste.workspace = true
prodef.workspace = true
rand.workspace = true
rand_distr.workspace = true
rand_xoshiro.workspace = true
rayon.workspace = true
serde.workspace = true
serde_arrays.workspace = true
serde_json5.workspace = true
typenum.workspace = true
thiserror.workspace = true
wcs.workspace = true

[lints]
workspace = true




