[package]
name = "ocnus"
version = "0.2.0"
authors = ["Andreas J. Weiss <ajefweiss@gmail.com>"]
edition = "2024"
license = "MIT License"
repository = "https://github.com/ajefweiss/ocnus/"
rust-version = "1.92"

[dependencies]
approx = "*"
chrono = "*"
criterion = "*"
derive_builder = "*"
derive_more = { version = "*", features = ["full"] }
dtw = "*"
env_logger = "*"
itertools = "*"
log = "*"
nalgebra = { version = "*", features = ["rayon", "serde-serialize"] }
num-traits = "*"
paste = "*"
rand = "*"
rand_distr = "*"
rand_xoshiro = "*"
rayon = "*"
serde = { version = "*", features = ["derive"] }
serde_arrays = "*"
serde_json5 = "*"
typenum = "*"
thiserror = "*"
wcs = { path = "../wcs-rs" }

bayesfm = { path = "/Users/ajweiss/Projects/bayesfm-rs" }
prodef = { path = "/Users/ajweiss/Projects/prodef-rs" }

[profile.bench]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[profile.test]
opt-level = 1

#[[bench]]
#name = "corem"
#harness = false

[[bench]]
name = "cylm"
harness = false

[lints.rust]
missing_docs = "deny"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[workspace]
members = [
    "ocnus_py",
]
resolver = "2"

