[package]
name = "ocnus"
version = "0.3.0"
authors = ["Andreas J. Weiss <ajefweiss@gmail.com>"]
edition = "2024"
license = "MIT License"
repository = "https://github.com/ajefweiss/ocnus/"
rust-version = "1.92"

[dependencies]
approx = "0.5.1"
chrono = "0.4.45"
criterion = "0.8.2"
derive_builder = "0.20.2"
derive_more = { version = "2.1.1", features = ["full"] }
dtw = "0.1.0"
env_logger = "0.11.11"
itertools = "0.15.0"
log = "0.4.33"
nalgebra = { version = "0.34.2", features = ["rayon", "serde-serialize"] }
num-traits = "0.2.19"
paste = "1.0.15"
rand = "0.10.2"
rand_distr = "0.6.0"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_arrays = "0.2.0"
serde_json5 = "0.2.1"
typenum = "1.20.1"
thiserror = "2.0.20"
wcs = { path = "../wcs-rs" }

bayesfm = { path = "../bayesfm-rs" }
prodef = { path = "../prodef-rs" }

[profile.bench]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[profile.test]
opt-level = 1

#[[bench]]
#name = "corem"
#harness = false

[[bench]]
name = "cylm"
harness = false

[lints.rust]
missing_docs = "deny"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[workspace]
members = [
    "ocnus_py",
]
resolver = "2"

