[package]
name = "ocnus-py"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ocnus_py"
crate-type = ["cdylib"]

[dependencies]
nalgebra = { version = "0.34.2", features = ["rayon", "serde-serialize"] }
numpy = "0.29.0"
paste = "1.0.15"
pyo3 = "0.29.2"
pyo3-log = "0.13.3"
rand = "0.10.2"

bayesfm = { path = "../../bayesfm-rs", features = ["pyo3"] }
prodef = { path = "../../prodef-rs", features = ["pyo3"] }
ocnus = { path = ".." }


[features]
f32 = []
